// Banco de questões do Atlas Vivo. Fica só no servidor: o gabarito (ans, ansText, steps, why)
// é enviado ao navegador apenas depois que a pessoa responde.
'use strict';
const B = 'Básica', I = 'Intermediária';
const q = (id, topic, diff, stem, opts, ans, ansText, why, extra) =>
  Object.assign({ id, topic, diff, stem, opts, ans, ansText, why }, extra);

module.exports = [
  { id: 'organizacao', title: 'Organização do corpo e homeostase', questions: [
    q('org1', 'Níveis de organização', B, 'Qual sequência apresenta os níveis de organização do corpo do mais simples ao mais complexo?',
      ['Tecido, célula, órgão, sistema.', 'Célula, tecido, órgão, sistema.', 'Órgão, tecido, célula, sistema.', 'Célula, órgão, tecido, sistema.'], 1,
      'Células formam tecidos, tecidos formam órgãos e órgãos formam sistemas.',
      ['O tecido é um conjunto de células, então a célula vem antes.', 'Correta. Cada nível é formado por unidades do nível anterior.', 'A ordem está invertida: o órgão é formado por tecidos.', 'O órgão é formado por tecidos, não o contrário.']),
    q('org2', 'Homeostase', B, 'Homeostase é:',
      ['a ausência total de variação no organismo.', 'o aumento contínuo da temperatura corporal.', 'a manutenção do meio interno dentro de limites compatíveis com a vida.', 'a troca de gases nos pulmões.'], 2,
      'O meio interno varia, mas mecanismos de regulação o mantêm dentro de uma faixa estreita.',
      ['As variáveis oscilam o tempo todo; o que se mantém é a faixa de variação.', 'Um aumento contínuo seria uma falha de regulação.', 'Correta. É um equilíbrio dinâmico, mantido por regulação.', 'Essa é a hematose, um dos processos que contribuem para a homeostase.']),
    q('org3', 'Homeostase', I, 'Em um dia quente, a temperatura corporal começa a subir e o corpo responde com suor e dilatação dos vasos da pele. Esse é um exemplo de:',
      ['retroalimentação negativa, pois a resposta reduz o desvio inicial.', 'retroalimentação positiva, pois a resposta amplia o desvio inicial.', 'digestão química.', 'ausência de regulação.'], 0,
      'Na retroalimentação negativa, a resposta se opõe à alteração que a provocou.',
      ['Correta. Suor e vasodilatação fazem a temperatura voltar a cair.', 'Na positiva, a resposta reforçaria o aumento de temperatura.', 'Digestão química é a quebra de moléculas por enzimas.', 'Há regulação: o desvio é detectado e corrigido.']),
  ] },
  { id: 'digestorio', title: 'Sistema digestório', questions: [
    q('dig1', 'Absorção', B, 'Em que órgão ocorre a maior parte da absorção de nutrientes?',
      ['Estômago.', 'Esôfago.', 'Intestino grosso.', 'Intestino delgado.'], 3,
      'Vilosidades e microvilosidades ampliam muito a superfície de absorção do intestino delgado.',
      ['No estômago começa a digestão das proteínas; a absorção é pequena.', 'O esôfago apenas conduz o alimento até o estômago.', 'O intestino grosso absorve principalmente água e sais.', 'Correta. É onde a maior parte dos nutrientes passa para o sangue.']),
    q('dig2', 'Digestão', B, 'A bile, produzida pelo fígado e armazenada na vesícula biliar, atua:',
      ['digerindo proteínas no estômago.', 'emulsificando gorduras no intestino delgado.', 'absorvendo água no intestino grosso.', 'digerindo amido na boca.'], 1,
      'A bile não tem enzimas: ela divide a gordura em gotículas e facilita a ação das lipases.',
      ['Quem inicia a digestão das proteínas no estômago é a pepsina.', 'Correta. A emulsificação aumenta a superfície de ação das lipases.', 'A bile não absorve água; isso é função da parede intestinal.', 'O amido começa a ser digerido pela amilase salivar.']),
    q('dig3', 'Digestão', I, 'A digestão química das proteínas começa no estômago porque ali:',
      ['a pepsina atua em meio ácido, mantido pelo ácido clorídrico.', 'a amilase salivar é ativada pelo pH ácido.', 'a bile quebra as proteínas em aminoácidos.', 'as vilosidades absorvem as proteínas inteiras.'], 0,
      'O ácido clorídrico ativa a pepsina, enzima que quebra proteínas em fragmentos menores.',
      ['Correta. A pepsina funciona bem no pH ácido do estômago.', 'A amilase digere amido e é inativada pelo pH ácido.', 'A bile age sobre gorduras e é liberada no intestino delgado.', 'Vilosidades ficam no intestino delgado e absorvem aminoácidos, não proteínas inteiras.']),
  ] },
  { id: 'respiratorio', title: 'Sistema respiratório', questions: [
    q('res1', 'Trocas gasosas', B, 'As trocas gasosas entre o ar e o sangue ocorrem:',
      ['na traqueia.', 'nos brônquios.', 'nos alvéolos pulmonares.', 'na laringe.'], 2,
      'Os alvéolos têm parede muito fina e são envolvidos por capilares.',
      ['A traqueia conduz o ar; sua parede é espessa.', 'Os brônquios distribuem o ar pelos pulmões, sem trocas.', 'Correta. É onde ocorre a hematose.', 'A laringe conduz o ar e abriga as pregas vocais.']),
    q('res2', 'Ventilação', B, 'Durante a inspiração, o diafragma:',
      ['relaxa e sobe, diminuindo o volume do tórax.', 'contrai e desce, aumentando o volume do tórax.', 'não participa do movimento.', 'contrai e sobe, expulsando o ar.'], 1,
      'Com o tórax maior, a pressão interna cai e o ar entra nos pulmões.',
      ['Isso descreve a expiração.', 'Correta. O aumento de volume reduz a pressão e o ar entra.', 'O diafragma é o principal músculo da respiração.', 'Ao contrair, o diafragma desce; e a entrada de ar é a inspiração.']),
    q('res3', 'Trocas gasosas', I, 'O oxigênio passa do ar alveolar para o sangue por:',
      ['transporte ativo, com gasto de ATP.', 'osmose, acompanhando a água.', 'fagocitose pelas hemácias.', 'difusão, do local de maior para o de menor concentração.'], 3,
      'O O₂ está mais concentrado no ar alveolar do que no sangue que chega aos pulmões.',
      ['Não há gasto de energia nem proteínas bombeando O₂.', 'Osmose é o movimento de água através de membrana.', 'Hemácias transportam O₂ ligado à hemoglobina; não fagocitam.', 'Correta. A diferença de concentração move o gás.']),
  ] },
  { id: 'cardiovascular', title: 'Sistema cardiovascular', questions: [
    q('q1', 'Circulação', B, 'Na circulação humana, qual vaso conduz sangue do ventrículo direito em direção aos pulmões?',
      ['Aorta.', 'Veia cava superior.', 'Artéria pulmonar.', 'Veia pulmonar.', 'Veia cava inferior.'], 2,
      'O ventrículo direito impulsiona sangue em direção aos pulmões pelas artérias pulmonares.',
      ['A aorta sai do ventrículo esquerdo e distribui sangue à circulação sistêmica.', 'A veia cava superior chega ao átrio direito; ela traz sangue ao coração.', 'Correta. É o vaso que sai do ventrículo direito rumo aos pulmões.', 'As veias pulmonares chegam ao átrio esquerdo, trazendo sangue dos pulmões.', 'A veia cava inferior também chega ao átrio direito.'],
      { pulm: 1, sec: 3, steps: ['Localize o ponto de partida: o ventrículo direito.', 'Pergunte para onde esse sangue precisa ir: aos pulmões, para as trocas gasosas.', 'Vaso que sai do coração é artéria. O que liga o ventrículo direito aos pulmões é a artéria pulmonar.'] }),
    q('q2', 'Vasos', B, 'Em qual tipo de vaso ocorrem as principais trocas de substâncias entre o sangue e as células dos tecidos?',
      ['Artérias de grande calibre.', 'Capilares.', 'Veias cavas.', 'Aorta.', 'Veias pulmonares.'], 1,
      'A parede fina dos capilares favorece a passagem de gases, nutrientes e resíduos.',
      ['Têm parede espessa e elástica: conduzem sangue sob pressão, sem trocas significativas.', 'Correta. A parede de uma camada de células favorece as trocas.', 'Conduzem o sangue dos tecidos de volta ao coração.', 'Distribui o sangue, mas sua parede espessa não permite trocas com as células.', 'Levam sangue dos pulmões ao coração.'],
      { sec: 4, steps: ['Trocas exigem parede fina e contato próximo com as células.', 'Capilares têm parede formada por uma única camada de células e formam redes nos tecidos.', 'Por isso, são os principais locais de troca.'] }),
    q('q3', 'Integração', I, 'Durante uma corrida, os músculos passam a consumir mais oxigênio e glicose. Qual conjunto de respostas contribui para atender a essa demanda?',
      ['Redução da frequência cardíaca e da ventilação.', 'Aumento da ventilação pulmonar e do fluxo de sangue para os músculos.', 'Interrupção da circulação pulmonar para priorizar a sistêmica.', 'Constrição dos vasos que irrigam os músculos em atividade.', 'Diminuição do retorno de sangue ao coração.'], 1,
      'Ventilação e circulação se ajustam juntas para levar mais O₂ e nutrientes aos músculos.',
      ['Reduzir frequência e ventilação diminuiria a oferta de O₂.', 'Correta. É a resposta integrada entre respiratório e cardiovascular.', 'As circulações estão em série: sem a pulmonar, o sangue não seria oxigenado.', 'Nos músculos ativos, os vasos se dilatam, o que aumenta o fluxo.', 'Menor retorno venoso reduziria o volume de sangue bombeado.'],
      { sec: 5, steps: ['Identifique a demanda: mais O₂ e nutrientes nos músculos.', 'A ventilação aumenta a entrada de O₂; a circulação acelera e direciona mais sangue aos músculos ativos.', 'Os dois sistemas respondem de forma integrada.'] }),
    q('q4', 'Circulação', B, 'Sobre as veias pulmonares, é correto afirmar que elas:',
      ['levam sangue do ventrículo direito aos pulmões.', 'desembocam no átrio direito.', 'conduzem sangue rico em oxigênio dos pulmões ao átrio esquerdo.', 'saem do ventrículo esquerdo em direção aos tecidos.', 'são os locais de troca gasosa nos alvéolos.'], 2,
      'Veias chegam ao coração; as pulmonares trazem sangue oxigenado ao átrio esquerdo.',
      ['Esse é o papel das artérias pulmonares.', 'Ao átrio direito chegam as veias cavas.', 'Correta.', 'Essa descrição corresponde à aorta.', 'As trocas ocorrem nos capilares que envolvem os alvéolos.'],
      { pulm: 1, sec: 3, steps: ['Veia é o vaso que chega ao coração.', 'Nos pulmões, o sangue recebe oxigênio.', 'Logo, as veias pulmonares trazem sangue rico em O₂ ao átrio esquerdo.'] }),
    q('q5', 'Vasos', I, 'Um estudante afirma: “Toda artéria transporta sangue rico em oxigênio”. Essa afirmação é:',
      ['correta, porque artérias sempre saem do coração.', 'incorreta, porque a artéria pulmonar transporta sangue relativamente pobre em oxigênio.', 'correta, porque o sangue arterial é vermelho e o venoso é azul.', 'incorreta, porque artérias chegam ao coração.', 'correta apenas na circulação pulmonar.'], 1,
      'A definição de artéria depende da direção do fluxo, não do teor de oxigênio.',
      ['Sair do coração define a artéria, mas não garante sangue rico em O₂.', 'Correta.', 'Vermelho e azul são convenções de diagrama; o sangue não fica azul.', 'Vasos que chegam ao coração são veias.', 'Na circulação pulmonar, a artéria leva justamente sangue pobre em O₂.'],
      { pulm: 1, sec: 2, steps: ['Lembre a definição: artéria conduz sangue para fora do coração.', 'A definição não menciona oxigênio.', 'A artéria pulmonar sai do ventrículo direito com sangue que voltou dos tecidos, pobre em O₂.'] }),
  ] },
  { id: 'urinario', title: 'Sistema urinário', questions: [
    q('uri1', 'Néfron', B, 'A unidade funcional do rim, responsável por filtrar o sangue e formar a urina, é:',
      ['o ureter.', 'a bexiga.', 'o néfron.', 'a uretra.'], 2,
      'Cada rim tem cerca de um milhão de néfrons, onde ocorrem filtração, reabsorção e secreção.',
      ['O ureter conduz a urina do rim à bexiga.', 'A bexiga armazena a urina.', 'Correta. É no néfron que a urina é formada.', 'A uretra conduz a urina para fora do corpo.']),
    q('uri2', 'Vias urinárias', B, 'Qual é o trajeto da urina depois de formada?',
      ['Rim, ureter, bexiga, uretra.', 'Rim, uretra, bexiga, ureter.', 'Bexiga, ureter, rim, uretra.', 'Rim, bexiga, ureter, uretra.'], 0,
      'Os ureteres levam a urina dos rins à bexiga; a uretra a conduz para fora.',
      ['Correta.', 'Ureter e uretra estão trocados: a uretra é o último trecho.', 'A urina é formada no rim, não na bexiga.', 'O ureter fica entre o rim e a bexiga.']),
    q('uri3', 'Equilíbrio hídrico', I, 'Após muitas horas sem beber água, aumenta a liberação do hormônio antidiurético (ADH). O efeito esperado é:',
      ['menor reabsorção de água e urina mais diluída.', 'maior reabsorção de água nos rins e urina mais concentrada.', 'interrupção da filtração do sangue.', 'eliminação de glicose na urina.'], 1,
      'O ADH torna os túbulos renais mais permeáveis à água, que volta ao sangue.',
      ['Esse é o efeito da falta de ADH.', 'Correta. O corpo conserva água e o volume de urina diminui.', 'A filtração continua; o que muda é quanta água é reabsorvida.', 'Glicose na urina está ligada a glicemia muito alta, não ao ADH.']),
  ] },
  { id: 'nervoso', title: 'Sistema nervoso', questions: [
    q('ner1', 'Neurônio', B, 'No neurônio, o impulso nervoso normalmente percorre o sentido:',
      ['axônio, corpo celular, dendritos.', 'corpo celular, dendritos, axônio.', 'axônio, dendritos, corpo celular.', 'dendritos, corpo celular, axônio.'], 3,
      'Dendritos recebem os sinais; o axônio os conduz até a célula seguinte.',
      ['Esse é o sentido inverso do habitual.', 'Os dendritos são a entrada do sinal, não uma etapa intermediária.', 'O axônio é a via de saída, não a de entrada.', 'Correta.']),
    q('ner2', 'Organização', B, 'Fazem parte do sistema nervoso central:',
      ['encéfalo e medula espinal.', 'nervos e gânglios.', 'apenas o cérebro.', 'medula espinal e nervos.'], 0,
      'Encéfalo e medula espinal formam o sistema nervoso central; nervos e gânglios, o periférico.',
      ['Correta.', 'Nervos e gânglios formam o sistema nervoso periférico.', 'O cérebro é só uma parte do encéfalo, e a medula espinal também é central.', 'Os nervos pertencem ao sistema nervoso periférico.']),
    q('ner3', 'Reflexos', I, 'Ao encostar a mão em uma superfície muito quente, você a retira antes de sentir a dor. Isso acontece porque:',
      ['o músculo se contrai sem participação de neurônios.', 'o cérebro decide a resposta antes do estímulo.', 'a resposta é integrada na medula espinal, sem depender primeiro do cérebro.', 'hormônios levam a informação mais rápido que os nervos.'], 2,
      'No arco reflexo, o neurônio sensitivo faz conexão na medula e o comando motor volta ao músculo.',
      ['A contração depende do neurônio motor.', 'O cérebro recebe a informação depois, quando a dor é percebida.', 'Correta. O caminho curto pela medula torna a resposta mais rápida.', 'A sinalização hormonal é mais lenta que a nervosa.']),
  ] },
  { id: 'endocrino', title: 'Sistema endócrino', questions: [
    q('end1', 'Glicemia', B, 'Qual hormônio reduz a concentração de glicose no sangue após uma refeição?',
      ['Glucagon.', 'Insulina.', 'Adrenalina.', 'Tiroxina.'], 1,
      'A insulina, produzida pelo pâncreas, favorece a entrada de glicose nas células.',
      ['O glucagon faz o oposto: eleva a glicemia no jejum.', 'Correta.', 'A adrenalina eleva a glicemia em situações de estresse.', 'A tiroxina regula o ritmo do metabolismo.']),
    q('end2', 'Sinalização', B, 'Os hormônios chegam às células-alvo principalmente:',
      ['por impulsos elétricos nos nervos.', 'por ductos que se abrem no tubo digestório.', 'pelo ar inspirado.', 'pela corrente sanguínea.'], 3,
      'Glândulas endócrinas não têm ductos: liberam os hormônios diretamente no sangue.',
      ['Essa é a sinalização do sistema nervoso.', 'Ductos são característicos de glândulas exócrinas.', 'O ar inspirado traz gases, não hormônios.', 'Correta.']),
    q('end3', 'Regulação', I, 'Quando a concentração de hormônios da tireoide no sangue aumenta, a hipófise reduz a liberação de TSH. Esse mecanismo é:',
      ['retroalimentação negativa.', 'retroalimentação positiva.', 'um arco reflexo.', 'digestão hormonal.'], 0,
      'O produto final inibe o estímulo que levou à sua produção, o que estabiliza sua concentração.',
      ['Correta.', 'Na positiva, o aumento do hormônio estimularia ainda mais TSH.', 'Arco reflexo é uma via nervosa rápida, com neurônios sensitivo e motor.', 'Esse termo não descreve um mecanismo de regulação.']),
  ] },
  { id: 'esqueletico', title: 'Sistema esquelético', questions: [
    q('esq1', 'Funções', B, 'Qual das funções abaixo NÃO é do sistema esquelético?',
      ['Sustentar o corpo.', 'Proteger órgãos internos.', 'Produzir bile.', 'Abrigar a medula óssea, que produz células do sangue.'], 2,
      'A bile é produzida pelo fígado, que pertence ao sistema digestório.',
      ['Sustentação é função do esqueleto.', 'Crânio e caixa torácica protegem encéfalo, coração e pulmões.', 'Correta. Quem produz bile é o fígado.', 'A medula óssea vermelha fica no interior de alguns ossos.']),
    q('esq2', 'Articulações', B, 'As estruturas que unem um osso a outro em uma articulação são:',
      ['os tendões.', 'os ligamentos.', 'as cartilagens costais.', 'os nervos.'], 1,
      'Ligamentos unem osso a osso; tendões unem músculo a osso.',
      ['Tendões prendem os músculos aos ossos.', 'Correta.', 'As cartilagens costais ligam as costelas ao esterno.', 'Nervos conduzem impulsos; não unem ossos.']),
    q('esq3', 'Medula óssea', I, 'A produção de hemácias, leucócitos e plaquetas ocorre:',
      ['na medula espinal.', 'na cartilagem articular.', 'no periósteo.', 'na medula óssea vermelha.'], 3,
      'A medula óssea vermelha é o tecido que forma as células do sangue (hematopoese).',
      ['A medula espinal é tecido nervoso, dentro da coluna vertebral.', 'A cartilagem articular reveste as extremidades dos ossos e reduz o atrito.', 'O periósteo é a membrana que reveste o osso por fora.', 'Correta.']),
  ] },
  { id: 'muscular', title: 'Sistema muscular', questions: [
    q('mus1', 'Tipos de tecido', B, 'O tecido muscular de contração voluntária, ligado aos ossos, é o:',
      ['estriado esquelético.', 'estriado cardíaco.', 'liso.', 'conjuntivo.'], 0,
      'O músculo estriado esquelético responde ao controle voluntário e move o esqueleto.',
      ['Correta.', 'O cardíaco forma o coração e tem contração involuntária.', 'O liso está na parede de vísceras e vasos; é involuntário.', 'O tecido conjuntivo não é um tecido muscular.']),
    q('mus2', 'Movimento', B, 'Ao flexionar o cotovelo, o bíceps se contrai enquanto o tríceps relaxa. Esses músculos são chamados de:',
      ['sinergistas.', 'involuntários.', 'antagonistas.', 'lisos.'], 2,
      'Músculos antagonistas produzem movimentos opostos na mesma articulação.',
      ['Sinergistas atuam juntos no mesmo movimento.', 'Os dois são músculos esqueléticos, de controle voluntário.', 'Correta.', 'Os dois são músculos estriados esqueléticos.']),
    q('mus3', 'Contração e energia', I, 'A fonte imediata de energia para a contração muscular é:',
      ['o ácido lático.', 'o ATP.', 'o gás carbônico.', 'a hemoglobina.'], 1,
      'A quebra do ATP fornece a energia para o deslizamento dos filamentos de actina e miosina.',
      ['O ácido lático é um produto da fermentação, não uma fonte de energia imediata.', 'Correta.', 'O gás carbônico é um resíduo da respiração celular.', 'A hemoglobina transporta oxigênio no sangue.']),
  ] },
  { id: 'tegumentar', title: 'Sistema tegumentar', questions: [
    q('teg1', 'Camadas da pele', B, 'A camada mais superficial da pele, formada por epitélio e sem vasos sanguíneos, é a:',
      ['derme.', 'epiderme.', 'hipoderme.', 'fáscia muscular.'], 1,
      'A epiderme é nutrida por difusão a partir dos vasos da derme, logo abaixo.',
      ['A derme fica abaixo da epiderme e tem vasos, nervos e glândulas.', 'Correta.', 'A hipoderme é a camada profunda, rica em gordura.', 'A fáscia envolve os músculos; não é camada da pele.']),
    q('teg2', 'Termorregulação', B, 'A evaporação do suor contribui para:',
      ['aquecer o corpo.', 'produzir vitamina C.', 'digerir gorduras.', 'resfriar o corpo.'], 3,
      'Ao evaporar, a água do suor retira calor da superfície da pele.',
      ['A evaporação retira calor; não aquece.', 'O corpo humano não produz vitamina C.', 'A digestão de gorduras ocorre no intestino delgado.', 'Correta.']),
    q('teg3', 'Proteção', I, 'A melanina, produzida por melanócitos da epiderme, tem como função principal:',
      ['proteger as células contra a radiação ultravioleta.', 'produzir suor.', 'impermeabilizar a pele.', 'transportar oxigênio.'], 0,
      'A melanina absorve parte da radiação ultravioleta e protege o DNA das células da pele.',
      ['Correta.', 'O suor é produzido pelas glândulas sudoríparas.', 'A impermeabilização depende principalmente da queratina.', 'O transporte de oxigênio é feito pela hemoglobina.']),
  ] },
  { id: 'linfatico', title: 'Sistema linfático e imunidade', questions: [
    q('lin1', 'Anatomia linfática', B, 'Uma função do sistema linfático é:',
      ['bombear sangue para as artérias.', 'digerir proteínas.', 'devolver ao sangue o líquido que saiu dos capilares para os tecidos.', 'produzir urina.'], 2,
      'Os vasos linfáticos recolhem o excesso de líquido intersticial e o devolvem à circulação.',
      ['Quem bombeia o sangue é o coração.', 'A digestão de proteínas ocorre no estômago e no intestino delgado.', 'Correta. Esse líquido, dentro dos vasos linfáticos, é a linfa.', 'A urina é formada nos rins.']),
    q('lin2', 'Imunidade', B, 'Os linfonodos atuam:',
      ['filtrando a linfa e abrigando células de defesa.', 'produzindo hemácias.', 'armazenando bile.', 'controlando a glicemia.'], 0,
      'Nos linfonodos, linfócitos entram em contato com microrganismos trazidos pela linfa.',
      ['Correta.', 'As hemácias são produzidas na medula óssea vermelha.', 'A bile é armazenada na vesícula biliar.', 'A glicemia é regulada por hormônios do pâncreas.']),
    q('lin3', 'Vacinas', I, 'As vacinas protegem porque:',
      ['fornecem anticorpos prontos, que duram a vida toda.', 'estimulam o organismo a produzir anticorpos e células de memória.', 'matam diretamente os microrganismos no sangue.', 'impedem qualquer contato com o agente causador.'], 1,
      'A vacina apresenta antígenos; o sistema imunitário responde e guarda memória dessa resposta.',
      ['Anticorpos prontos são fornecidos pelo soro, e a proteção é temporária.', 'Correta. A memória torna a resposta futura mais rápida e intensa.', 'A vacina não age sobre o microrganismo; ela prepara a defesa do corpo.', 'A vacina não evita o contato; prepara o corpo para responder a ele.']),
  ] },
  { id: 'reprodutor', title: 'Sistema reprodutor', questions: [
    q('rep1', 'Anatomia masculina', B, 'Os espermatozoides são produzidos:',
      ['na próstata.', 'na uretra.', 'nas vesículas seminais.', 'nos testículos.'], 3,
      'A produção ocorre nos túbulos seminíferos, no interior dos testículos.',
      ['A próstata produz parte do líquido do sêmen.', 'A uretra conduz o sêmen e a urina para fora.', 'As vesículas seminais produzem parte do líquido do sêmen.', 'Correta.']),
    q('rep2', 'Anatomia feminina', B, 'Em condições normais, a fecundação ocorre:',
      ['no ovário.', 'na tuba uterina.', 'no útero.', 'na vagina.'], 1,
      'O encontro dos gametas acontece na tuba uterina; o embrião depois se implanta no útero.',
      ['O ovário libera o ovócito, mas a fecundação não ocorre nele.', 'Correta.', 'No útero ocorre a implantação do embrião.', 'A vagina recebe os espermatozoides, que seguem até as tubas.']),
    q('rep3', 'Regulação hormonal', I, 'No ciclo menstrual, a ovulação é desencadeada por um pico do hormônio:',
      ['progesterona.', 'testosterona.', 'LH (hormônio luteinizante).', 'insulina.'], 2,
      'O pico de LH, liberado pela hipófise, provoca a liberação do ovócito pelo ovário.',
      ['A progesterona predomina depois da ovulação e mantém o endométrio.', 'A testosterona é o principal hormônio sexual masculino.', 'Correta.', 'A insulina regula a glicemia.']),
  ] },
  { id: 'integracao', title: 'Integração e revisão', questions: [
    q('int1', 'Exercício físico', I, 'Durante o exercício intenso, aumentam a frequência cardíaca e a respiratória. O objetivo principal desses ajustes é:',
      ['levar mais O₂ aos músculos e remover mais CO₂.', 'reduzir a temperatura dos músculos.', 'acelerar a digestão.', 'diminuir o fluxo de sangue nos músculos.'], 0,
      'Músculos ativos consomem mais O₂ e produzem mais CO₂; circulação e ventilação acompanham a demanda.',
      ['Correta.', 'A temperatura é controlada principalmente pelo suor e pela circulação na pele.', 'No exercício, o fluxo de sangue para o tubo digestório diminui.', 'O fluxo de sangue nos músculos ativos aumenta.']),
    q('int2', 'Desidratação', I, 'Em uma pessoa desidratada, espera-se:',
      ['menor liberação de ADH e urina diluída.', 'aumento da produção de suor e de urina.', 'maior liberação de ADH, urina concentrada e sede.', 'parada da circulação sanguínea.'], 2,
      'Sistema nervoso, endócrino e urinário atuam juntos para conservar água.',
      ['Com pouca água, a liberação de ADH aumenta.', 'O corpo reduz as perdas de água, não as aumenta.', 'Correta. Os rins reabsorvem mais água e a sede estimula a reposição.', 'A circulação continua; o corpo ajusta o volume de líquidos.']),
    q('int3', 'Alimentação', I, 'Depois de uma refeição rica em carboidratos, a glicose absorvida no intestino:',
      ['é eliminada diretamente pelos rins.', 'entra no sangue, e a insulina favorece sua entrada nas células.', 'fica retida no estômago até a refeição seguinte.', 'é transportada pelos nervos até os músculos.'], 1,
      'Digestório, cardiovascular e endócrino se integram: absorção, transporte e regulação da glicemia.',
      ['Em condições normais, os rins reabsorvem toda a glicose filtrada.', 'Correta.', 'A absorção ocorre no intestino delgado, e a glicose segue para o sangue.', 'Nervos conduzem impulsos; quem transporta nutrientes é o sangue.']),
  ] },
];

// Questões respondidas no modelo 3D: a pessoa clica na estrutura. view.sys = sistemas mostrados;
// target = sistema e trechos do nome (em português ou FMA) das estruturas aceitas como certas.
const mq = (quiz, id, topic, diff, stem, show, sys, parts, ansText, extra) =>
  module.exports.find(z => z.id === quiz).questions.push(Object.assign({ id, kind: 'model', topic, diff, stem, view: { sys: show }, target: { sys, q: parts }, ansText }, extra));
mq('digestorio', 'dig4', 'Digestão', B, 'No modelo 3D, clique no órgão que produz a bile.', ['digestorio'], 'digestorio', ['fígado'],
  'O fígado produz a bile, que fica armazenada na vesícula biliar e é lançada no duodeno.');
mq('respiratorio', 'res4', 'Vias respiratórias', B, 'No modelo 3D, clique na traqueia.', ['respiratorio'], 'respiratorio', ['traqueia'],
  'A traqueia é o tubo que leva o ar da laringe até os brônquios.');
mq('cardiovascular', 'q6', 'Circulação', B, 'No modelo 3D, clique na veia cava inferior.', ['cardiovascular'], 'cardiovascular', ['veia cava inferior'],
  'A veia cava inferior traz ao átrio direito o sangue que volta da parte inferior do corpo.', { sec: 3 });
mq('urinario', 'uri4', 'Vias urinárias', B, 'No modelo 3D, clique no órgão que armazena a urina.', ['urinario'], 'urinario', ['bexiga'],
  'A bexiga urinária armazena a urina que chega pelos ureteres, até ela ser eliminada pela uretra.');
mq('nervoso', 'ner4', 'Organização', B, 'No modelo 3D, clique no cerebelo.', ['nervoso'], 'nervoso', ['cerebelo'],
  'O cerebelo fica na parte posterior e inferior do encéfalo e coordena o equilíbrio e a precisão dos movimentos.');
mq('endocrino', 'end4', 'Glândulas', B, 'No modelo 3D, clique em uma das glândulas suprarrenais.', ['endocrino', 'urinario'], 'endocrino', ['suprarrenal'],
  'As suprarrenais ficam sobre os rins e produzem adrenalina e cortisol.');
mq('esqueletico', 'esq4', 'Organização', B, 'No modelo 3D, clique no fêmur direito. Lembre: em vista frontal, o lado direito do corpo aparece à esquerda de quem observa.', ['esqueletico'], 'esqueletico', ['fêmur direito'],
  'O fêmur é o osso da coxa e pertence ao esqueleto apendicular.');
mq('muscular', 'mus4', 'Movimento', B, 'No modelo 3D, clique no bíceps braquial de um dos braços.', ['muscular'], 'muscular', ['bíceps braquial'],
  'O bíceps braquial fica na face anterior do braço e flexiona o cotovelo; o tríceps, na face posterior, é seu antagonista.');
mq('linfatico', 'lin4', 'Anatomia linfática', B, 'No modelo 3D, clique no baço.', ['linfatico', 'digestorio'], 'linfatico', ['baço'],
  'O baço fica no lado esquerdo do abdome, filtra o sangue e remove hemácias envelhecidas.');
mq('reprodutor', 'rep4', 'Anatomia masculina', B, 'No modelo 3D, clique em um dos órgãos que produzem os espermatozoides.', ['reprodutor'], 'reprodutor', ['testículo'],
  'Os espermatozoides são produzidos nos testículos, dentro dos túbulos seminíferos.');
mq('integracao', 'int4', 'Desidratação', I, 'No modelo 3D, clique em um dos órgãos que passam a reabsorver mais água sob ação do ADH.', ['urinario', 'digestorio', 'respiratorio'], 'urinario', ['rim '],
  'Os rins: sob ação do ADH, os néfrons reabsorvem mais água e a urina sai mais concentrada.');
